stages:
  - test

variables:
  # Set up your environment variables here (e.g., DATABASE_URL, SECRET_KEY, etc.)
  DJANGO_SETTINGS_MODULE: "your_project.settings.ci"

test:
  stage: test
  image: python:3.9
  services:
    - postgres:latest
  before_script:
    - pip install -r requirements.txt
    - python manage.py makemigrations --check --dry-run
    - python manage.py migrate --noinput
  script:
    - python manage.py test